version: "3.7"
services:
  java:
    image: openjdk:10-jdk
    entrypoint: /bin/jshell
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M